const images = {

  bgLoader: require('../assets/images/bg_loader.png'),
  bgMain:   require('../assets/images/bg_main.png'),

  onboardGirl1: require('../assets/images/onboard_girl_1.png'),
  onboardGirl2: require('../assets/images/onboard_girl_2.png'),
  onboardGirl3: require('../assets/images/onboard_girl_3.png'),
  onboardGirl4: require('../assets/images/onboard_girl_4.png'),
  onboardGirl5: require('../assets/images/onboard_girl_5.png'),

  planet1:        require('../assets/images/planet_1.png'),
  planet2:        require('../assets/images/planet_2.png'),
  planet3:        require('../assets/images/planet_3.png'),
  planet4:        require('../assets/images/planet_4.png'),
  planet5:        require('../assets/images/planet_5.png'),
  planetSettings: require('../assets/images/planet_settings.png'),

  article1:  require('../assets/images/articles/article_1.png'),
  article2:  require('../assets/images/articles/article_2.png'),
  article3:  require('../assets/images/articles/article_3.png'),
  article4:  require('../assets/images/articles/article_4.png'),
  article5:  require('../assets/images/articles/article_5.png'),
  article6:  require('../assets/images/articles/article_6.png'),
  article7:  require('../assets/images/articles/article_7.png'),
  article8:  require('../assets/images/articles/article_8.png'),
  article9:  require('../assets/images/articles/article_9.png'),
  article10: require('../assets/images/articles/article_10.png'),
  article11: require('../assets/images/articles/article_11.png'),
  article12: require('../assets/images/articles/article_12.png'),

  game: {
    item1:  require('../assets/images/game/item_1.png'),
    item2:  require('../assets/images/game/item_2.png'),
    item3:  require('../assets/images/game/item_3.png'),
    item4:  require('../assets/images/game/item_4.png'),
    item5:  require('../assets/images/game/item_5.png'),
    item6:  require('../assets/images/game/item_6.png'),
    item7:  require('../assets/images/game/item_7.png'),
    item8:  require('../assets/images/game/item_8.png'),
    item9:  require('../assets/images/game/item_9.png'),
    item10: require('../assets/images/game/item_10.png'),
    item11: require('../assets/images/game/item_11.png'),
    item12: require('../assets/images/game/item_12.png'),
    item13: require('../assets/images/game/item_13.png'),
    item14: require('../assets/images/game/item_14.png'),
    item15: require('../assets/images/game/item_15.png'),
    item16: require('../assets/images/game/item_16.png'),
    item17: require('../assets/images/game/item_17.png'),
    item18: require('../assets/images/game/item_18.png'),
    item19: require('../assets/images/game/item_19.png'),
    item20: require('../assets/images/game/item_20.png'),
    item21: require('../assets/images/game/item_21.png'),
    item22: require('../assets/images/game/item_22.png'),
    item23: require('../assets/images/game/item_23.png'),
    item24: require('../assets/images/game/item_24.png'),
    item25: require('../assets/images/game/item_25.png'),
    item26: require('../assets/images/game/item_26.png'),
    item27: require('../assets/images/game/item_27.png'),
    item28: require('../assets/images/game/item_28.png'),
    item29: require('../assets/images/game/item_29.png'),
    item30: require('../assets/images/game/item_30.png'),
    item31: require('../assets/images/game/item_31.png'),
    item32: require('../assets/images/game/item_32.png'),
    item33: require('../assets/images/game/item_33.png'),
    item34: require('../assets/images/game/item_34.png'),
    item35: require('../assets/images/game/item_35.png'),
    item36: require('../assets/images/game/item_36.png'),
    item37: require('../assets/images/game/item_37.png'),
    item38: require('../assets/images/game/item_38.png'),
    item39: require('../assets/images/game/item_39.png'),
    item40: require('../assets/images/game/item_40.png'),
  },
};

export default images;